version: '3.8'

volumes:
  db_mongo:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: abn_kafka_zookeeper
    env_file:
      - compose/envs/zookeeper.env
    ports: 
      - "2181:2181"
    restart: unless-stopped
    networks:
      - kafka_net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: abn_kafka
    depends_on:
      - zookeeper
    env_file:
      - compose/envs/kafka.env
    ports:
      - "9092:9092"
    networks:
      - kafka_net

  proy_producer:
    image: proy_cron
    container_name: abn_producer
    command: ["python", "main.py"]
    env_file:
      - compose/envs/worker.env
    volumes:
      - ./abrenet_scheduler:/app
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - kafka_net

  proy_worker:
    image: proy_cron
    container_name: abn_worker
    command: ["python", "main.py"]
    env_file:
      - compose/envs/worker.env
      - compose/envs/mongo.env
    volumes:
      - ./abrenet_worker:/app
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - kafka_net

  proy_streamlit:
    image: proy_cron
    container_name: abn_streamlit
    command: ["streamlit", "run", "main.py"]
    env_file:
      - compose/envs/worker.env
      - compose/envs/mongo.env
    volumes:
      - ./streamlit:/app
    ports: 
      - "8501:8501"
    depends_on:
      - kafka
    restart: unless-stopped
    networks:
      - kafka_net
  mongo:
    image: proy_mongo
    container_name: abn_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - compose/envs/mongo.env
    volumes:
      - db_mongo:/data/db
    networks:
      - kafka_net


networks:
  kafka_net:
    name: kafka_net
    driver: bridge
